language: php
sudo: true
dist: trusty

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

before_script:
  - composer update

addons:
  sonarcloud:
    organization: "pingcheng-github"

script:
  - vendor/bin/phpunit
  - vendor/bin/php-coveralls -v
  - sonar-scanner